services:
  - type: web
    name: lol-elo-guesser-api
    env: python
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: RIOT_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: "3.11"
